//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mfEntities : DbContext
    {
        public mfEntities()
            : base("name=mfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tb_ads_request> tb_ads_request { get; set; }
        public DbSet<tb_content> tb_content { get; set; }
        public DbSet<tb_courses> tb_courses { get; set; }
        public DbSet<tb_courses_status> tb_courses_status { get; set; }
        public DbSet<tb_dc> tb_dc { get; set; }
        public DbSet<tb_dc_type> tb_dc_type { get; set; }
        public DbSet<tb_donors> tb_donors { get; set; }
        public DbSet<tb_file_on_page> tb_file_on_page { get; set; }
        public DbSet<tb_files> tb_files { get; set; }
        public DbSet<tb_files_category> tb_files_category { get; set; }
        public DbSet<tb_gallery> tb_gallery { get; set; }
        public DbSet<tb_gallery_category> tb_gallery_category { get; set; }
        public DbSet<tb_lang> tb_lang { get; set; }
        public DbSet<tb_news> tb_news { get; set; }
        public DbSet<tb_news_type> tb_news_type { get; set; }
        public DbSet<tb_pages> tb_pages { get; set; }
        public DbSet<tb_prints> tb_prints { get; set; }
        public DbSet<tb_prints_content> tb_prints_content { get; set; }
        public DbSet<tb_projects> tb_projects { get; set; }
        public DbSet<tb_question_categorys> tb_question_categorys { get; set; }
        public DbSet<tb_question_sub_categorys> tb_question_sub_categorys { get; set; }
        public DbSet<tb_questions> tb_questions { get; set; }
        public DbSet<tb_subscription_request> tb_subscription_request { get; set; }
        public DbSet<tb_user_in_role> tb_user_in_role { get; set; }
        public DbSet<tb_user_roles> tb_user_roles { get; set; }
        public DbSet<tb_users> tb_users { get; set; }
        public DbSet<tb_subscription_news_request> tb_subscription_news_request { get; set; }
        public DbSet<tb_question_request> tb_question_request { get; set; }
        public DbSet<tb_organization> tb_organization { get; set; }
        public DbSet<tb_tasks> tb_tasks { get; set; }
        public DbSet<tb_about_organization> tb_about_organization { get; set; }
        public DbSet<tb_structure_organization> tb_structure_organization { get; set; }
        public DbSet<tb_region> tb_region { get; set; }
        public DbSet<tb_economic> tb_economic { get; set; }
        public DbSet<tb_vacancy> tb_vacancy { get; set; }
        public DbSet<tb_secondary_files> tb_secondary_files { get; set; }
        public DbSet<tb_info_mf> tb_info_mf { get; set; }
        public DbSet<tb_ministr_mf> tb_ministr_mf { get; set; }
        public DbSet<tb_zam_mf> tb_zam_mf { get; set; }
        public DbSet<tb_ruk_depart_mf> tb_ruk_depart_mf { get; set; }
        public DbSet<secondary_file_type> secondary_file_type { get; set; }
        public DbSet<tb_events_leaders> tb_events_leaders { get; set; }
        public DbSet<tb_event_leaders_category> tb_event_leaders_category { get; set; }
    }
}
