//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class secondary_file_type
    {
        public secondary_file_type()
        {
            this.tb_secondary_files = new HashSet<tb_secondary_files>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<tb_secondary_files> tb_secondary_files { get; set; }
    }
}
