//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_courses_status
    {
        public tb_courses_status()
        {
            this.tb_courses = new HashSet<tb_courses>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<tb_courses> tb_courses { get; set; }
    }
}
