//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_event_leaders_category
    {
        public tb_event_leaders_category()
        {
            this.tb_events_leaders = new HashSet<tb_events_leaders>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
        public virtual tb_ministr_mf tb_ministr_mf { get; set; }
        public virtual ICollection<tb_events_leaders> tb_events_leaders { get; set; }
    }
}
