//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_files
    {
        public tb_files()
        {
            this.tb_file_on_page = new HashSet<tb_file_on_page>();
        }
    
        public int id { get; set; }
        public System.DateTime date_create { get; set; }
        public int category_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string file_name { get; set; }
        public int lang_id { get; set; }
        public Nullable<System.DateTime> public_date { get; set; }
        public bool is_main { get; set; }
        public bool is_active { get; set; }
    
        public virtual ICollection<tb_file_on_page> tb_file_on_page { get; set; }
        public virtual tb_files_category tb_files_category { get; set; }
        public virtual tb_lang tb_lang { get; set; }
        public virtual tb_organization tb_organization { get; set; }
    }
}
