//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_file_on_page
    {
        public int id { get; set; }
        public int file_id { get; set; }
        public int content_page_id { get; set; }
    
        public virtual tb_content tb_content { get; set; }
        public virtual tb_files tb_files { get; set; }
    }
}
