//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_gallery_category
    {
        public tb_gallery_category()
        {
            this.tb_gallery = new HashSet<tb_gallery>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> order_id { get; set; }
        public string image { get; set; }
        public bool is_active { get; set; }
    
        public virtual ICollection<tb_gallery> tb_gallery { get; set; }
    }
}
