//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_info_mf
    {
        public tb_info_mf()
        {
            this.tb_zam_mf = new HashSet<tb_zam_mf>();
            this.tb_ruk_depart_mf = new HashSet<tb_ruk_depart_mf>();
        }
    
        public int Id { get; set; }
    
        public virtual tb_ministr_mf tb_ministr_mf { get; set; }
        public virtual ICollection<tb_zam_mf> tb_zam_mf { get; set; }
        public virtual ICollection<tb_ruk_depart_mf> tb_ruk_depart_mf { get; set; }
        public virtual tb_lang tb_lang { get; set; }
    }
}
