//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_lang
    {
        public tb_lang()
        {
            this.tb_content = new HashSet<tb_content>();
            this.tb_dc_type = new HashSet<tb_dc_type>();
            this.tb_files = new HashSet<tb_files>();
            this.tb_files_category = new HashSet<tb_files_category>();
            this.tb_news_type = new HashSet<tb_news_type>();
            this.tb_question_categorys = new HashSet<tb_question_categorys>();
            this.tb_question_sub_categorys = new HashSet<tb_question_sub_categorys>();
            this.tb_tasks = new HashSet<tb_tasks>();
            this.tb_about_organization = new HashSet<tb_about_organization>();
            this.tb_structure_organization = new HashSet<tb_structure_organization>();
            this.tb_organization = new HashSet<tb_organization>();
            this.tb_economic = new HashSet<tb_economic>();
            this.tb_vacancy = new HashSet<tb_vacancy>();
            this.tb_info_mf = new HashSet<tb_info_mf>();
            this.tb_projects = new HashSet<tb_projects>();
            this.tb_events_leaders = new HashSet<tb_events_leaders>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public bool is_active { get; set; }
    
        public virtual ICollection<tb_content> tb_content { get; set; }
        public virtual ICollection<tb_dc_type> tb_dc_type { get; set; }
        public virtual ICollection<tb_files> tb_files { get; set; }
        public virtual ICollection<tb_files_category> tb_files_category { get; set; }
        public virtual ICollection<tb_news_type> tb_news_type { get; set; }
        public virtual ICollection<tb_question_categorys> tb_question_categorys { get; set; }
        public virtual ICollection<tb_question_sub_categorys> tb_question_sub_categorys { get; set; }
        public virtual ICollection<tb_tasks> tb_tasks { get; set; }
        public virtual ICollection<tb_about_organization> tb_about_organization { get; set; }
        public virtual ICollection<tb_structure_organization> tb_structure_organization { get; set; }
        public virtual ICollection<tb_organization> tb_organization { get; set; }
        public virtual ICollection<tb_economic> tb_economic { get; set; }
        public virtual ICollection<tb_vacancy> tb_vacancy { get; set; }
        public virtual ICollection<tb_info_mf> tb_info_mf { get; set; }
        public virtual ICollection<tb_projects> tb_projects { get; set; }
        public virtual ICollection<tb_events_leaders> tb_events_leaders { get; set; }
    }
}
