//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ministr_mf
    {
        public tb_ministr_mf()
        {
            this.tb_event_leaders_category = new HashSet<tb_event_leaders_category>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string full_name { get; set; }
        public string last_name { get; set; }
        public string bio { get; set; }
        public string logo_file_name { get; set; }
        public string contact_info { get; set; }
    
        public virtual tb_info_mf tb_info_mf { get; set; }
        public virtual ICollection<tb_event_leaders_category> tb_event_leaders_category { get; set; }
    }
}
