//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_news_type
    {
        public tb_news_type()
        {
            this.tb_news = new HashSet<tb_news>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool is_active { get; set; }
        public bool show_on_main { get; set; }
        public int lang { get; set; }
    
        public virtual tb_lang tb_lang { get; set; }
        public virtual ICollection<tb_news> tb_news { get; set; }
    }
}
