//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_organization
    {
        public tb_organization()
        {
            this.tb_files = new HashSet<tb_files>();
            this.tb_structure_organization = new HashSet<tb_structure_organization>();
            this.tb_dc = new HashSet<tb_dc>();
            this.tb_tasks = new HashSet<tb_tasks>();
            this.tb_about_organization = new HashSet<tb_about_organization>();
            this.tb_news = new HashSet<tb_news>();
            this.tb_vacancy = new HashSet<tb_vacancy>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public string index { get; set; }
    
        public virtual ICollection<tb_files> tb_files { get; set; }
        public virtual ICollection<tb_structure_organization> tb_structure_organization { get; set; }
        public virtual ICollection<tb_dc> tb_dc { get; set; }
        public virtual ICollection<tb_tasks> tb_tasks { get; set; }
        public virtual ICollection<tb_about_organization> tb_about_organization { get; set; }
        public virtual ICollection<tb_news> tb_news { get; set; }
        public virtual tb_region tb_region { get; set; }
        public virtual tb_lang tb_lang { get; set; }
        public virtual ICollection<tb_vacancy> tb_vacancy { get; set; }
    }
}
