//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_prints_content
    {
        public int id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<System.DateTime> date_print { get; set; }
        public string image { get; set; }
        public string text { get; set; }
        public Nullable<int> prints_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual tb_prints tb_prints { get; set; }
    }
}
