//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_prints
    {
        public tb_prints()
        {
            this.tb_prints_content = new HashSet<tb_prints_content>();
            this.tb_subscription_request = new HashSet<tb_subscription_request>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> published_since { get; set; }
        public bool is_active { get; set; }
    
        public virtual ICollection<tb_prints_content> tb_prints_content { get; set; }
        public virtual ICollection<tb_subscription_request> tb_subscription_request { get; set; }
    }
}
