//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_questions
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public int category_sub_id { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string question_title { get; set; }
        public Nullable<System.DateTime> question_date { get; set; }
        public string question { get; set; }
        public string question_author_fio { get; set; }
        public string question_author_email { get; set; }
        public Nullable<System.DateTime> answer_date { get; set; }
        public string answer_author_fio { get; set; }
        public string answer_author_position { get; set; }
        public string answer { get; set; }
        public bool is_active { get; set; }
    
        public virtual tb_question_categorys tb_question_categorys { get; set; }
        public virtual tb_question_sub_categorys tb_question_sub_categorys { get; set; }
    }
}
