//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_question_sub_categorys
    {
        public tb_question_sub_categorys()
        {
            this.tb_questions = new HashSet<tb_questions>();
            this.tb_question_request = new HashSet<tb_question_request>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int lang { get; set; }
        public bool is_active { get; set; }
    
        public virtual tb_lang tb_lang { get; set; }
        public virtual ICollection<tb_questions> tb_questions { get; set; }
        public virtual ICollection<tb_question_request> tb_question_request { get; set; }
    }
}
