//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_structure_organization
    {
        public int Id { get; set; }
        public string name_director { get; set; }
        public string last_name_director { get; set; }
        public string full_name_director { get; set; }
        public string picture_director { get; set; }
        public string bio_director { get; set; }
        public string text_for_nachalniki { get; set; }
        public bool is_active { get; set; }
    
        public virtual tb_organization tb_organization { get; set; }
        public virtual tb_lang tb_lang { get; set; }
    }
}
