//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_subscription_request
    {
        public int id { get; set; }
        public string fio { get; set; }
        public string email { get; set; }
        public string organization { get; set; }
        public string position { get; set; }
        public string phone { get; set; }
        public Nullable<int> print_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public bool is_active { get; set; }
    
        public virtual tb_prints tb_prints { get; set; }
    }
}
