//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_users
    {
        public tb_users()
        {
            this.tb_user_in_role = new HashSet<tb_user_in_role>();
        }
    
        public int id { get; set; }
        public string fio { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public bool is_active { get; set; }
    
        public virtual ICollection<tb_user_in_role> tb_user_in_role { get; set; }
    }
}
