//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mf_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_zam_mf
    {
        public int Id { get; set; }
        public string doljnost { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public string full_name { get; set; }
        public string bio { get; set; }
        public string logo_file_name { get; set; }
    
        public virtual tb_info_mf tb_info_mf { get; set; }
    }
}
